version: 2
jobs:
  build:
    working_directory: ~/api
    docker:
      - image: microsoft/dotnet:2.1-sdk
      - image: mongo:3.4.4-jessie
    environment:
      - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet build ./firenotes-api.sln
      - run: dotnet test firenotes-api.Tests