version: 2
jobs:
  build:
    working_directory: ~/api
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
      - image: mongo:3.6.7-jessie
    environment:
      - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build ./firenotes-api.sln
      - run: dotnet test firenotes-api.Tests